import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Layout.module.css'

const Layout = ( { children } ) => {
  return ( 
        <div className={styles.container}>
        <Head>
          <title>Ten Flags Theme Park</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

          <div className={styles.navbar}>
            <div className={styles.navbar_container}>
              <div className={styles.logo}>
                <Image src={"/logo.png"} width={100} height={100} alt={"logo"} />
              </div>
              
              <div className={styles.menu}>
                <p className={styles.menu_items}>
                  HOME
                </p>
                <p className={styles.menu_items}>
                  HIGHLIGHTS
                </p>
                <p className={styles.menu_items}>
                  COMMUNITY
                </p>
              </div>

              <div className={styles.social}>
              <Image src={"/icons/facebook.png"} width={60} height={60} alt={"facebook"} className={styles.social_items} />
              <Image src={"/icons/twitter.png"} width={60} height={60} alt={"twitter"} className={styles.social_items} />
              <Image src={"/icons/instagram.png"} width={60} height={60} alt={"instagram"} className={styles.social_items} />
              </div>
            </div>
          </div>
          <div className={styles.content}>
            { children }
          </div>
          </div>
     );
}
 
export default Layout;