/* eslint-disable @next/next/link-passhref */
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { Parallax, Background } from 'react-parallax';

import AwesomeSlider from 'react-awesome-slider';
import 'react-awesome-slider/dist/styles.css';
import withAutoplay from 'react-awesome-slider/dist/autoplay';

import {
    EmailShareButton,
    EmailIcon,
    FacebookShareButton,
    FacebookIcon,
    WhatsappShareButton,
    WhatsappIcon,
    TwitterShareButton,
    TwitterIcon,
  } from "react-share";

const Layout = ( { children } ) => {
  const AutoplaySlider = withAutoplay(AwesomeSlider);
    return ( 
        <div className={styles.container}>
        <Head>
          <title>Ten Flags Theme Park</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
          {/* MAINCARD */}
  
          <div className={styles.mainCard}>

          <div className={styles.social2}></div>
  
            {/* LOGOCARD */}
  
            <div className={styles.logoCard}>
              {/* <div className={styles.mainTitle}></div> */}
              <Link href="/">
                  <Image src={"/logo.png"} width={150} height={150} alt="Ten Flags Logo" className={styles.logo} />
              </Link>
            </div>
  
            {/* LOGOCARD END */}

            <div className={styles.slider}>

              <AutoplaySlider play={true} cancelOnInteraction={false} interval={8000} buttons={false} bullets={false} showTimer={false}>

                <div data-src="/Spin.jpg" ></div>
                <div data-src="/Paint.jpg" />
                <div data-src="/Quads.png" />
                <div data-src="/Rides.jpg" />

              </AutoplaySlider>

            </div>

            <div className={styles.social}>

              <FacebookIcon size={30} round={true} className={styles.icon} />
              <TwitterIcon size={30} round={true} className={styles.icon} />
              <WhatsappIcon size={30} round={true} className={styles.icon} />
              {/* <EmailIcon size={30} round={true} className={styles.icon} /> */}

            </div>
  
          </div>
  
          {/* MAINCARD END */}

          <div className={styles.buffer}>
            <div className={styles.buffer2}>
              <p1 className={styles.p2thin}>WELCOME TO</p1><p1 className={styles.p2bold}>TEN FLAGS</p1><p1 className={styles.p2thin}>THEME PARK</p1>
            </div>
          </div>
  
          <main className={styles.main}>
          <div className={styles.sponsors}></div>
          <div className={styles.mainContainer}>
            
          { children }

          </div>
  
            {/* FOOTER */}
  
            <div className={styles.footer}>
            
              <div className={styles.subFooter}>
                <div className={styles.shareFooter}>
                  {/* TWITTER */}
                  <TwitterShareButton className={styles.shareButton} url={"https://tenflagsthemepark.co.za"}>
                    <TwitterIcon size={40} round={true} />
                  </TwitterShareButton>
  
                  {/* FACEBOOK */}
                  <FacebookShareButton className={styles.shareButton} quote={"https://tenflagsthemepark.co.za"} hashtag={"testing"}>
                    <FacebookIcon size={40} round={true} />
                  </FacebookShareButton>
  
                  {/* EMAIL */}
                  <EmailShareButton className={styles.shareButton} url={"https://tenflagsthemepark.co.za"}>
                    <EmailIcon size={40} round={true} />
                  </EmailShareButton>
                </div>
                Ten Flags Theme Park, Farm Karussel,<br/>
                572 Rex Rd, Rustenburg, 0300, South Africa<br/><br/><br/>

                0149410823
              </div>

              {/* <div className={styles.subFooter}>
                
              </div> */}

            </div>
  
            {/* FOOTER END */}
  
          </main>
      </div>
     );
}
 
export default Layout;